import type { NextPage } from 'next'
import Head from 'next/head'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from "next-i18next/serverSideTranslations"

import Page from "../components/core/Page";
import Navigation from '../components/navigation/Navigation'

import HomeSection from "../components/sections/HomeSection"

const Home: NextPage = () => {
  const { t } = useTranslation('common')

  return (
    <Page>
      <Head>
        <title>icabetong</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation/>
      </main>
    </Page>
  )
}

type HomeProps = {
  locale: string
}
export const getStaticProps = async ({ locale }: HomeProps) => ({
  props: {
    ...await serverSideTranslations(locale, ['common'])
  }
})

export default Home