import type { NextPage } from 'next'
import Head from 'next/head'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from "next-i18next/serverSideTranslations"

import Navigation from '../components/navigation/Navigation'

import HeroSection from "../components/sections/HeroSection"
import { LocaleProps } from '../shared/types'

const Home: NextPage = () => {
  const { t } = useTranslation('common')

  return (
    <>
      <Head>
        <title>icabetong</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative bg-russian text-azureish-white min-h-screen mx-auto">
        <HeroSection/>
        <div className="absolute inset-0">
          <Navigation/>
        </div>
        {t("hero_greet")}
      </main>
    </>
  )
}

type HomeProps = LocaleProps
export const getStaticProps = async ({ locale }: HomeProps) => ({
  props: {
    ...await serverSideTranslations(locale, ['common'])
  }
})

export default Home